// All 54 African countries. Names match the display names stored in the database
// and (where present) the feature names in public/data/africa-continent.geojson.
export const AFRICAN_COUNTRIES = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Ivory Coast",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
] as const;

export type AfricanCountry = (typeof AFRICAN_COUNTRIES)[number];

export const COUNTRIES = ["All Countries", ...AFRICAN_COUNTRIES] as const;

export const COUNTRY_FLAGS: Record<string, string> = {
  Algeria: "🇩🇿",
  Angola: "🇦🇴",
  Benin: "🇧🇯",
  Botswana: "🇧🇼",
  "Burkina Faso": "🇧🇫",
  Burundi: "🇧🇮",
  "Cabo Verde": "🇨🇻",
  Cameroon: "🇨🇲",
  "Central African Republic": "🇨🇫",
  Chad: "🇹🇩",
  Comoros: "🇰🇲",
  "Democratic Republic of the Congo": "🇨🇩",
  "Republic of the Congo": "🇨🇬",
  "Ivory Coast": "🇨🇮",
  Djibouti: "🇩🇯",
  Egypt: "🇪🇬",
  "Equatorial Guinea": "🇬🇶",
  Eritrea: "🇪🇷",
  Eswatini: "🇸🇿",
  Ethiopia: "🇪🇹",
  Gabon: "🇬🇦",
  Gambia: "🇬🇲",
  Ghana: "🇬🇭",
  Guinea: "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  Kenya: "🇰🇪",
  Lesotho: "🇱🇸",
  Liberia: "🇱🇷",
  Libya: "🇱🇾",
  Madagascar: "🇲🇬",
  Malawi: "🇲🇼",
  Mali: "🇲🇱",
  Mauritania: "🇲🇷",
  Mauritius: "🇲🇺",
  Morocco: "🇲🇦",
  Mozambique: "🇲🇿",
  Namibia: "🇳🇦",
  Niger: "🇳🇪",
  Nigeria: "🇳🇬",
  Rwanda: "🇷🇼",
  "Sao Tome and Principe": "🇸🇹",
  Senegal: "🇸🇳",
  Seychelles: "🇸🇨",
  "Sierra Leone": "🇸🇱",
  Somalia: "🇸🇴",
  "South Africa": "🇿🇦",
  "South Sudan": "🇸🇸",
  Sudan: "🇸🇩",
  Tanzania: "🇹🇿",
  Togo: "🇹🇬",
  Tunisia: "🇹🇳",
  Uganda: "🇺🇬",
  Zambia: "🇿🇲",
  Zimbabwe: "🇿🇼",
};

// ISO 3166-1 alpha-3 → display name, used by the choropleth map (geojson feature ids).
export const ISO3_TO_COUNTRY: Record<string, string> = {
  DZA: "Algeria",
  AGO: "Angola",
  BEN: "Benin",
  BWA: "Botswana",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CPV: "Cabo Verde",
  CMR: "Cameroon",
  CAF: "Central African Republic",
  TCD: "Chad",
  COM: "Comoros",
  COD: "Democratic Republic of the Congo",
  COG: "Republic of the Congo",
  CIV: "Ivory Coast",
  DJI: "Djibouti",
  EGY: "Egypt",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  SWZ: "Eswatini",
  ETH: "Ethiopia",
  GAB: "Gabon",
  GMB: "Gambia",
  GHA: "Ghana",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  KEN: "Kenya",
  LSO: "Lesotho",
  LBR: "Liberia",
  LBY: "Libya",
  MDG: "Madagascar",
  MWI: "Malawi",
  MLI: "Mali",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MAR: "Morocco",
  MOZ: "Mozambique",
  NAM: "Namibia",
  NER: "Niger",
  NGA: "Nigeria",
  RWA: "Rwanda",
  STP: "Sao Tome and Principe",
  SEN: "Senegal",
  SYC: "Seychelles",
  SLE: "Sierra Leone",
  SOM: "Somalia",
  ZAF: "South Africa",
  SSD: "South Sudan",
  SDN: "Sudan",
  TZA: "Tanzania",
  TGO: "Togo",
  TUN: "Tunisia",
  UGA: "Uganda",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
};

// ISO 3166-1 alpha-2 → display name, used by API sources that return alpha-2 codes.
export const ISO2_TO_COUNTRY: Record<string, string> = {
  DZ: "Algeria",
  AO: "Angola",
  BJ: "Benin",
  BW: "Botswana",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  CM: "Cameroon",
  CF: "Central African Republic",
  TD: "Chad",
  KM: "Comoros",
  CD: "Democratic Republic of the Congo",
  CG: "Republic of the Congo",
  CI: "Ivory Coast",
  DJ: "Djibouti",
  EG: "Egypt",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  SZ: "Eswatini",
  ET: "Ethiopia",
  GA: "Gabon",
  GM: "Gambia",
  GH: "Ghana",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  KE: "Kenya",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  MG: "Madagascar",
  MW: "Malawi",
  ML: "Mali",
  MR: "Mauritania",
  MU: "Mauritius",
  MA: "Morocco",
  MZ: "Mozambique",
  NA: "Namibia",
  NE: "Niger",
  NG: "Nigeria",
  RW: "Rwanda",
  ST: "Sao Tome and Principe",
  SN: "Senegal",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  SD: "Sudan",
  TZ: "Tanzania",
  TG: "Togo",
  TN: "Tunisia",
  UG: "Uganda",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
