export const COUNTRIES = [
  "All Countries",
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Democratic Republic of Congo",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Republic of Congo",
  "Rwanda",
  "Senegal",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
] as const;

export const COUNTRY_FLAGS: Record<string, string> = {
  Algeria: "🇩🇿",
  Angola: "🇦🇴",
  Benin: "🇧🇯",
  Botswana: "🇧🇼",
  "Burkina Faso": "🇧🇫",
  Burundi: "🇧🇮",
  Cameroon: "🇨🇲",
  "Central African Republic": "🇨🇫",
  Chad: "🇹🇩",
  "Democratic Republic of Congo": "🇨🇩",
  Djibouti: "🇩🇯",
  Egypt: "🇪🇬",
  "Equatorial Guinea": "🇬🇶",
  Eritrea: "🇪🇷",
  Eswatini: "🇸🇿",
  Ethiopia: "🇪🇹",
  Gabon: "🇬🇦",
  Gambia: "🇬🇲",
  Ghana: "🇬🇭",
  Guinea: "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  Kenya: "🇰🇪",
  Lesotho: "🇱🇸",
  Liberia: "🇱🇷",
  Libya: "🇱🇾",
  Madagascar: "🇲🇬",
  Malawi: "🇲🇼",
  Mali: "🇲🇱",
  Mauritania: "🇲🇷",
  Morocco: "🇲🇦",
  Mozambique: "🇲🇿",
  Namibia: "🇳🇦",
  Niger: "🇳🇪",
  Nigeria: "🇳🇬",
  "Republic of Congo": "🇨🇬",
  Rwanda: "🇷🇼",
  Senegal: "🇸🇳",
  "Sierra Leone": "🇸🇱",
  Somalia: "🇸🇴",
  "South Africa": "🇿🇦",
  "South Sudan": "🇸🇸",
  Sudan: "🇸🇩",
  Tanzania: "🇹🇿",
  Togo: "🇹🇬",
  Tunisia: "🇹🇳",
  Uganda: "🇺🇬",
  Zambia: "🇿🇲",
  Zimbabwe: "🇿🇼",
};
